"""removed query_run_id from docuemnt_chunks

Revision ID: 224deced40f2
Revises: 3e8c9905dff8
Create Date: 2026-08-12 06:54:11.593508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '224deced40f2'
down_revision: Union[str, Sequence[str], None] = '3e8c9905dff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_chunks_query_run_id_fkey'), 'document_chunks', type_='foreignkey')
    op.drop_column('document_chunks', 'query_run_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('query_run_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('document_chunks_query_run_id_fkey'), 'document_chunks', 'query_runs', ['query_run_id'], ['id'])
    # ### end Alembic commands ###
