"""query run and query citation models

Revision ID: 3e8c9905dff8
Revises: 419c8828fae5
Create Date: 2026-08-12 06:04:53.334842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3e8c9905dff8'
down_revision: Union[str, Sequence[str], None] = '419c8828fae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_run_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('excerpt', sa.String(), nullable=False),
    sa.Column('citation_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('document_chunks', sa.Column('query_run_id', sa.UUID(), nullable=False))
    op.add_column('document_chunks', sa.Column('chunk_id', sa.UUID(), nullable=False))
    op.add_column('document_chunks', sa.Column('excerpt', sa.String(), nullable=False))
    op.add_column('document_chunks', sa.Column('citation_order', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'document_chunks', 'document_chunks', ['chunk_id'], ['id'])
    op.create_foreign_key(None, 'document_chunks', 'query_runs', ['query_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_column('document_chunks', 'citation_order')
    op.drop_column('document_chunks', 'excerpt')
    op.drop_column('document_chunks', 'chunk_id')
    op.drop_column('document_chunks', 'query_run_id')
    op.drop_table('query_citations')
    op.drop_table('query_runs')
    # ### end Alembic commands ###
