"""add embedding metadata to ingestion runs

Revision ID: 419c8828fae5
Revises: 59e8ab83a83c
Create Date: 2026-08-09 12:11:41.624541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '419c8828fae5'
down_revision: Union[str, Sequence[str], None] = '59e8ab83a83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_runs3', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('ingestion_runs3', sa.Column('embedding_dimensions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_runs3', 'embedding_dimensions')
    op.drop_column('ingestion_runs3', 'embedding_model')
    # ### end Alembic commands ###
