"""make token count nullable

Revision ID: 59e8ab83a83c
Revises: d47abb1b3508
Create Date: 2026-08-09 06:26:27.818678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '59e8ab83a83c'
down_revision: Union[str, Sequence[str], None] = 'd47abb1b3508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'token_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'token_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
