"""added 2 new columns for run started at and completed at

Revision ID: 88f28dde6499
Revises: 567d665fe5ef
Create Date: 2026-08-01 10:09:37.390470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88f28dde6499'
down_revision: Union[str, Sequence[str], None] = '567d665fe5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_runs2')
    op.add_column('ingestion_runs3', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ingestion_runs3', sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_runs3', 'completed_at')
    op.drop_column('ingestion_runs3', 'started_at')
    op.create_table('ingestion_runs2',
    sa.Column('ingestion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ingestion_id', name=op.f('ingestion_runs2_pkey'))
    )
    # ### end Alembic commands ###
