"""fixed document_chunks

Revision ID: 96397a364c45
Revises: 224deced40f2
Create Date: 2026-08-12 06:57:02.204795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '96397a364c45'
down_revision: Union[str, Sequence[str], None] = '224deced40f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_chunks_chunk_id_fkey'), 'document_chunks', type_='foreignkey')
    op.drop_column('document_chunks', 'excerpt')
    op.drop_column('document_chunks', 'chunk_id')
    op.drop_column('document_chunks', 'citation_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('citation_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('document_chunks', sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('document_chunks', sa.Column('excerpt', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('document_chunks_chunk_id_fkey'), 'document_chunks', 'document_chunks', ['chunk_id'], ['id'])
    # ### end Alembic commands ###
