"""add core ingestion data models

Revision ID: d3a9dad21c16
Revises: 88f28dde6499
Create Date: 2026-08-01 19:31:58.779737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'd3a9dad21c16'
down_revision: Union[str, Sequence[str], None] = '88f28dde6499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_storage_path', sa.String(length=2048), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('section_heading', sa.String(length=500), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_document_index')
    )
    op.add_column('ingestion_runs3', sa.Column('document_url', sa.Text(), nullable=False))
    op.add_column('ingestion_runs3', sa.Column('document_id', sa.UUID(), nullable=True))
    op.add_column('ingestion_runs3', sa.Column('error_code', sa.String(length=100), nullable=True))
    op.add_column('ingestion_runs3', sa.Column('error_message', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'ingestion_runs3', 'documents', ['document_id'], ['id'])
    op.drop_column('ingestion_runs3', 'source_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_runs3', sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ingestion_runs3', type_='foreignkey')
    op.drop_column('ingestion_runs3', 'error_message')
    op.drop_column('ingestion_runs3', 'error_code')
    op.drop_column('ingestion_runs3', 'document_id')
    op.drop_column('ingestion_runs3', 'document_url')
    op.drop_table('document_chunks')
    op.drop_table('documents')
    # ### end Alembic commands ###
